package code;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alex
*/
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class panel extends javax.swing.JFrame {
public String a,b,c, coloress;
private Thread musicas;
public AudioClip choy;
public AudioClip diedo;

public AudioClip elchoy;
public AudioClip caza;
    /**
     * Creates new form panel
     */
    public int asdf, camino;
    public int btn=0,avk=0,bd,sues, pele, suitch, vueltas=1,ra,otro;
    public int mus=0, der=0, espe, inten=0, pasos=0,habilidad=2;
    public String hero;
    //------------ HEROE_STATS_POR_DEFECTO ---------------------
    int hep=300, atak=25, defe=20, exp=10, lev=1;
    //----------------- ENEMIGOS -------------------------------
    int hpe, yhp;
    entidades jefe=new entidades("EL CHOY", 700, 100, 100, 100, 1);
    entidades caz=new entidades("CAZARRECOMPENSAS", 500, 50, 50, 50, 1);  
    entidades vbot=new entidades("Vaca-bot", 300, 30, 30, 30, 1);    
    entidades sold=new entidades("Soldado", 110, 20, 15, 1, 1);
    entidades arc=new entidades("Arquero", 80, 24, 20, 2, 1);
    entidades caba=new entidades("Caballero negro", 150, 15, 25, 3, 1);
    entidades pic=new entidades("Picaro", 40, 30, 30, 3, 1);
    entidades sil=new entidades("Silva", 280, 14, 15, 5, 1);
    entidades vac=new entidades("una... vaca?", 1000, 6, 5, 20, 1);    
   //-------------------- HEROE -------------------------------
    entidades her= new entidades(hero, hep, atak, defe, exp, lev);
    
    public panel() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subirlv = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nombrep = new javax.swing.JLabel();
        exper = new javax.swing.JLabel();
        stav = new javax.swing.JLabel();
        staa = new javax.swing.JLabel();
        nivels = new javax.swing.JLabel();
        stad = new javax.swing.JLabel();
        subv = new javax.swing.JButton();
        suba = new javax.swing.JButton();
        subd = new javax.swing.JButton();
        colo1 = new javax.swing.JPanel();
        con = new javax.swing.JFrame();
        desplayear = new javax.swing.JButton();
        playear = new javax.swing.JButton();
        obten = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        let = new javax.swing.JButton();
        let2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        let3 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        finav = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        juego = new javax.swing.JPanel();
        config = new javax.swing.JButton();
        ava_atk = new javax.swing.JButton();
        bus_def = new javax.swing.JButton();
        sui_esc = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Nom = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        atk = new javax.swing.JLabel();
        lv = new javax.swing.JLabel();
        xp = new javax.swing.JLabel();
        def = new javax.swing.JLabel();
        vida4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        abilidad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Nom3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        vida5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subLV = new javax.swing.JButton();
        izquierda = new javax.swing.JLabel();
        enfrente = new javax.swing.JLabel();
        derecha = new javax.swing.JLabel();
        retroceder = new javax.swing.JLabel();
        vaco = new javax.swing.JLabel();
        pantalla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dialogo = new javax.swing.JTextArea();
        barra = new javax.swing.JLabel();
        abilidad1 = new javax.swing.JButton();
        colo = new javax.swing.JPanel();
        titulo = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        muertos = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        subirlv.setBounds(120,100,325,275);
        subirlv.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Vitalidad");
        subirlv.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel10.setText("Ataque");
        subirlv.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        jLabel11.setText("Defensa");
        subirlv.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        jLabel12.setText("Nivel:");
        subirlv.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel13.setText("Experiencia:");
        subirlv.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Vani", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("*se necesita 10 puntos de experiencia por cada nivel");
        subirlv.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel15.setText("añade 10 pts");
        subirlv.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 30));

        jLabel16.setText("añade 2 pts");
        subirlv.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 20));

        jLabel17.setText("añade 3 pts");
        subirlv.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, 30));

        nombrep.setText("------");
        subirlv.getContentPane().add(nombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));
        subirlv.getContentPane().add(exper, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 40, 20));
        subirlv.getContentPane().add(stav, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 30));
        subirlv.getContentPane().add(staa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 60, 30));
        subirlv.getContentPane().add(nivels, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 40, 20));
        subirlv.getContentPane().add(stad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 60, 30));

        subv.setText("Subir nivel");
        subv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subvActionPerformed(evt);
            }
        });
        subirlv.getContentPane().add(subv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        suba.setText("Subir nivel");
        suba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subaActionPerformed(evt);
            }
        });
        subirlv.getContentPane().add(suba, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        subd.setText("Subir nivel");
        subd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subdActionPerformed(evt);
            }
        });
        subirlv.getContentPane().add(subd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        colo1.setVisible(false);
        colo1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout colo1Layout = new javax.swing.GroupLayout(colo1);
        colo1.setLayout(colo1Layout);
        colo1Layout.setHorizontalGroup(
            colo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        colo1Layout.setVerticalGroup(
            colo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        subirlv.getContentPane().add(colo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 330, 270));

        con.setBounds(200,150,220,300);

        desplayear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kiki.gif"))); // NOI18N
        desplayear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplayearActionPerformed(evt);
            }
        });

        playear.setVisible(false);
        playear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kirby.gif"))); // NOI18N
        playear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playearActionPerformed(evt);
            }
        });

        obten.setForeground(new java.awt.Color(0, 102, 102));
        obten.setText("cian");
        obten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(23, 104, 145));
        jButton2.setText("azul");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(249, 116, 27));
        jButton3.setText("naranja");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("gris");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setText("    Color de fondo");

        let.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        let.setText("segoe sc");
        let.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letActionPerformed(evt);
            }
        });

        let2.setFont(new java.awt.Font("Webdings", 0, 11)); // NOI18N
        let2.setText("wasco s");
        let2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                let2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Letra");

        let3.setText("default");
        let3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                let3ActionPerformed(evt);
            }
        });

        jLabel24.setText("Musica");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conLayout = new javax.swing.GroupLayout(con.getContentPane());
        con.getContentPane().setLayout(conLayout);
        conLayout.setHorizontalGroup(
            conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(obten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(let2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(let3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(let, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desplayear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(106, 106, 106)
                .addComponent(jLabel24)
                .addGap(48, 48, 48))
        );
        conLayout.setVerticalGroup(
            conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24))
                .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(let, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(let2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obten)
                            .addComponent(let3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(conLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(conLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(conLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(desplayear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        finav.setBackground(new java.awt.Color(0, 0, 0));
        finav.setBounds(50,30,300,150);
        finav.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Si");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        finav.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jButton6.setText("NO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        finav.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Encerio deseas terminar tu aventura aqui?");
        finav.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 280, 20));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        finav.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 380, 190));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("vaaacos");
        setBackground(new java.awt.Color(9, 70, 3));
        setBounds(new java.awt.Rectangle(300, 100, 720, 474));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        juego.setVisible(false);
        juego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/512px-Cog_font_awesome.png"))); // NOI18N
        config.setVisible(false);
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });
        juego.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 40, 40));

        ava_atk.setVisible(false);
        ava_atk.setBackground(new java.awt.Color(51, 51, 51));
        ava_atk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/atacar.png"))); // NOI18N
        ava_atk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ava_atkActionPerformed(evt);
            }
        });
        juego.add(ava_atk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 50, 50));

        bus_def.setVisible(false);
        bus_def.setBackground(new java.awt.Color(51, 51, 51));
        bus_def.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/defender.png"))); // NOI18N
        bus_def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus_defActionPerformed(evt);
            }
        });
        juego.add(bus_def, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 50, 50));

        sui_esc.setVisible(false);
        sui_esc.setBackground(new java.awt.Color(0, 0, 0));
        sui_esc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/escapar.png"))); // NOI18N
        sui_esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sui_escActionPerformed(evt);
            }
        });
        juego.add(sui_esc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 60, 50));

        Nombre.setVisible(false);
        Nombre.setText("Tu");
        juego.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 20));

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        juego.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jPanel1.setVisible(false);
        jPanel1.setBackground(new java.awt.Color(105, 60, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        Nom.setForeground(new java.awt.Color(255, 255, 51));
        Nom.setText("----");

        vida.setForeground(new java.awt.Color(255, 0, 0));
        vida.setText("----");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Vida:");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Ataque:");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Defensa:");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Nivel:");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Experiencia:");

        atk.setForeground(new java.awt.Color(0, 153, 153));
        atk.setText("----");

        lv.setForeground(new java.awt.Color(204, 0, 204));
        lv.setText("----");

        xp.setForeground(new java.awt.Color(0, 255, 204));
        xp.setText("----");

        def.setForeground(new java.awt.Color(0, 153, 153));
        def.setText("----");

        vida4.setForeground(new java.awt.Color(255, 0, 0));
        vida4.setText("----");

        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vida4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atk, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(def, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(xp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lv, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vida4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(def, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lv, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        juego.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 162, -1));

        abilidad.setBackground(new java.awt.Color(0, 0, 0));
        abilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/SkillV.png"))); // NOI18N
        abilidad.setVisible(false);
        abilidad.setEnabled(false);
        abilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abilidadActionPerformed(evt);
            }
        });
        juego.add(abilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 50, 50));

        jPanel4.setVisible(false);
        jPanel4.setBackground(new java.awt.Color(102, 102, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        Nom3.setForeground(new java.awt.Color(255, 255, 51));
        Nom3.setText("----");

        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Nombre:");

        vida3.setForeground(new java.awt.Color(255, 0, 0));
        vida3.setText("----");
        vida.setText("250");

        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Vitalidad:");

        vida5.setForeground(new java.awt.Color(255, 0, 0));
        vida5.setText("----");
        vida.setText("250");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("/");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nom3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(vida5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vida5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        juego.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 162, -1));

        subLV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Sin título.png"))); // NOI18N
        subLV.setVisible(false);
        subLV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subLVActionPerformed(evt);
            }
        });
        juego.add(subLV, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 40, 40));
        subLV.getAccessibleContext().setAccessibleDescription("");

        izquierda.setForeground(new java.awt.Color(51, 255, 255));
        izquierda.setVisible(false);
        izquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/izquierda.png"))); // NOI18N
        izquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaMouseClicked(evt);
            }
        });
        juego.add(izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        enfrente.setVisible(false);
        enfrente.setForeground(new java.awt.Color(51, 255, 255));
        enfrente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/enfrente.png"))); // NOI18N
        enfrente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enfrenteMouseClicked(evt);
            }
        });
        juego.add(enfrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        derecha.setForeground(new java.awt.Color(51, 255, 255));
        derecha.setVisible(false);
        derecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/derecha.png"))); // NOI18N
        derecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaMouseClicked(evt);
            }
        });
        juego.add(derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        retroceder.setForeground(new java.awt.Color(102, 255, 255));
        retroceder.setVisible(false);
        retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/retroceder.png"))); // NOI18N
        retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retrocederMouseClicked(evt);
            }
        });
        juego.add(retroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        vaco.setVisible(false);
        vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/vaaco.png"))); // NOI18N
        juego.add(vaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 90, 120));

        pantalla.setVisible(false);
        pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/2 way(izquierda-derecha).png"))); // NOI18N
        juego.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 540, 280));

        dialogo.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleBackground"));
        dialogo.setColumns(20);
        dialogo.setRows(5);
        dialogo.setText("Hace tiempo atrás\nUn ser maligno conocido como...\n\"El Choy\"");
        jScrollPane1.setViewportView(dialogo);

        juego.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 330, 110));

        barra.setVisible(false);
        barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra0.png"))); // NOI18N
        juego.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        abilidad1.setBackground(new java.awt.Color(0, 0, 0));
        abilidad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/SkillC.png"))); // NOI18N
        abilidad1.setVisible(false);
        abilidad1.setEnabled(false);
        abilidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abilidad1ActionPerformed(evt);
            }
        });
        juego.add(abilidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 50, 50));

        colo.setBackground(new java.awt.Color(102, 0, 0));
        colo.setFocusable(false);
        colo.setRequestFocusEnabled(false);
        colo.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout coloLayout = new javax.swing.GroupLayout(colo);
        colo.setLayout(coloLayout);
        coloLayout.setHorizontalGroup(
            coloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        coloLayout.setVerticalGroup(
            coloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        juego.add(colo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 750, 440));

        getContentPane().add(juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setForeground(new java.awt.Color(204, 204, 204));
        jButton7.setText("Nuevo Juego");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        titulo.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 140, 40));

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setForeground(new java.awt.Color(204, 204, 204));
        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        titulo.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 140, 40));

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setForeground(new java.awt.Color(204, 204, 204));
        jButton9.setText("Continuar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        titulo.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 140, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/titulo.gif"))); // NOI18N
        titulo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 490));

        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        muertos.setBackground(new java.awt.Color(0, 0, 0));
        muertos.setVisible(false);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/died.gif"))); // NOI18N

        javax.swing.GroupLayout muertosLayout = new javax.swing.GroupLayout(muertos);
        muertos.setLayout(muertosLayout);
        muertosLayout.setHorizontalGroup(
            muertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, muertosLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(40, 40, 40))
        );
        muertosLayout.setVerticalGroup(
            muertosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(muertosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel25)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(muertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // SEGUN EL MOMENTO, NOS DA EL TEXTO DE LAS OPCIONES DISPONIBLES Y UNOS DATOS EXTRA EN PANTALLA
        //TAMBIEN NOS INTRODUCE A LA HISTORIA Y CAMBIA LOS PARAMETROS DE LOS BOTONES
        String t1;
        if(btn==0){
        hero=Nombre.getText();
        Nombre.setVisible(false);
        Nom.setText(hero);}
        btn++;
        if(btn==8){btn=7;}
        switch(btn){
            case 1:
                t1=("Haciendose rápido con el poder"
                + "\nTomó control de Cowsville"
                + "\nEliminando a todo el que se le opusiera");
                pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/2.png"))); // NOI18N
                pantalla.setVisible(true);
                dialogo.setText(t1);                
                break;
            case 2:
                  t1 = ("Esclavisó a toda la población\n"
                + " Y los forzó a hacer trabajos forzados");
            pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/3.png"))); // NOI18N
            dialogo.setText(t1);
                break;
            case 3: 
                   t1 = ("Con el poder que había obtenido\n"
                + "Formó un ejercito y creó la fábrica de\n"
                        + "vaca-bots más grande del mundo");
            pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/1.png"))); // NOI18N
            dialogo.setText(t1);break;
            case 4:
                t1=("Rebelde: ¿Enserio no recuerdas nada de eso?\n"
                + "Valla que te afectó la amnesia\nComo sea, te llevaré con el líder rebelde\n"
                + "\nEl sabrá que hacer contigo");
                pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/vmuere.png"))); // NOI18N
                dialogo.setText(t1);
                break;
            case 5:
                t1 = ("Narrador: Mientras nuestros heroes avanzaban\n Una vaca bot apareció por detrás de ellos\nY atacó al rebelde"
                        + "\n\n Rebelde: AAAAAAHHHHH");
                dialogo.setText(t1);
              pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/vmuere2.png")));  break;
            case 6:
                pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/pantallazo.png")));
                t1 = ("Narrador: A partir de ahora estas sólo\n¿Quien será ese tal Choy?\nNo importa, habrá que darle una paliza");
                dialogo.setText(t1);
                break;      
            case 7:
                String t3=("\n\n¿A donde vas a ir?");
                batallas(1);
                subirE();
                subLV.setVisible(true);
                pantalla.setVisible(true);
                yhp=her.hp; vida4.setText(Integer.toString(her.hp));
                vida.setText(Integer.toString(hep));
                dialogo.setText(t3); 
                jButton1.setVisible(false); 
                jPanel1.setVisible(true);
                config.setVisible(true);
                atk.setText(Integer.toString(atak));
                def.setText(Integer.toString(defe));
                lv.setText(Integer.toString(lev));
                xp.setText(Integer.toString(exp));
                
                break;
            case 8:
                muertos.setVisible(true);
                juego.setVisible(false);
                break;
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ava_atkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ava_atkActionPerformed
        // TODO add your handling code here:
        switch(vueltas) {
            //CASO 2: INICIAMOS EL MODO DE PELEA, MANDAMOS DATOS DE ATK, DEF, Y RECIBIMOS LOS DAÑOS TOTALES
        case 2:
            
            habilidad++;
            if(habilidad==8)habilidad=7;
        switch(habilidad){
            case 1:
                break;
            case 2:
                break;
            case 3:
                barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra20.png")));
                break;
            case 4:
                barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra40.png")));
                break;
            case 5:
                barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra60.png")));
                break;
            case 6:
                barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra80.png")));
                break;
            case 7:
                barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra100.png")));
                abilidad.setEnabled(true);
                abilidad1.setEnabled(true);
                break;
        }
        switch(pele){
            case 0:
                b=sold.peleas(atak, defe);
                hpe=hpe-(atak-sold.deff);
                yhp=yhp-(sold.atf-(defe/2));
                break;
            case 1:
                b=arc.peleas(atak, defe);
                hpe=hpe-(atak-arc.deff);
                yhp=yhp-(arc.atf-(defe/2));
                break;
            case 2:
                b=caba.peleas(atak, defe);
                hpe=hpe-(atak-caba.deff);
                yhp=yhp-(caba.atf-(defe/2));
                break;
            case 3:
                b=pic.peleas(atak, defe);
                hpe=hpe-(atak-pic.deff);
                yhp=yhp-(pic.atf-(defe/2));
                break;
            case 4:
                b=sil.peleas(atak, defe);
                hpe=hpe-(atak-sil.deff);
                yhp=yhp-(sil.atf-(defe/2));
                break;
            case 5:
                b=vac.peleas(atak, defe);
                hpe=hpe-(atak-vac.deff);
                yhp=yhp-(vac.atf-(defe/2));
                break;
            case 6:
                b=jefe.peleas(atak, defe);
                hpe=hpe-(atak-jefe.deff);
                yhp=yhp-(jefe.atf-(defe/2));
                break;
            case 10:
                b=caz.peleas(atak, defe);
                hpe=hpe-(atak-caz.deff);
                yhp=yhp-(caz.atf-(defe/2));
                break;
            case 11:
                  b=vbot.peleas(atak, defe);
                hpe=hpe-(atak-vbot.deff);
                yhp=yhp-(vbot.atf-(defe/2)); break;
        }
        //COLOCACION EN PANTALLA DE LOS DATOS FINALES Y YA CALCULADOS
        dialogo.setText(b);
        if(hpe>1 && yhp>1){
        vida.setText(Integer.toString(yhp));
        vida3.setText(Integer.toString(hpe));}
        else{//AL DERROTAR O MORIR, AQUI SE MANDA A PANTALLA LO OCURRIDO
            if(yhp>1){
        vida.setText(Integer.toString(yhp));
        jPanel4.setVisible(false);
        vueltas=1;
        dialogo.setText("Has derrotado a"+ Nom3.getText());
        
        cerrar();
            if(pasos==700){
                caza.stop();
            }
            if(pasos==2000){
                choy.stop();
            }
            if(pasos>2001){
                elchoy.stop();}}
            else{
        if(hpe>1){
        muertos.setVisible(true);
        juego.setVisible(false);
        if(pasos==700){
                caza.stop();
                diedo.play();
            }
            if(pasos==2000){
                choy.stop();
                diedo.play();
            }
            if(pasos>2001){
                elchoy.stop();
                diedo.play();}}}
            }
        break;
            
        }
    }//GEN-LAST:event_ava_atkActionPerformed

    private void bus_defActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus_defActionPerformed
        // TODO add your handling code here:
        switch(vueltas){
                //CALCULO DE DATOS AL DEFENDERSE
            case 2:
                switch(pele){
            case 0:
                b=sold.peleas(atak, defe);
                if(sold.ram>18)yhp=yhp-(sold.atf-defe);
                break;
            case 1:
                b=arc.peleas(atak, defe);
                if(arc.ram>18)yhp=yhp-(arc.atf-defe);
                break;
            case 2:
                b=caba.peleas(atak, defe);
                if(caba.ram>18)yhp=yhp-(caba.atf-defe);
                break;
            case 3:
                b=pic.peleas(atak, defe);
                if(pic.ram>18)yhp=yhp-(pic.atf-defe);
                break;
            case 4:
                b=sil.peleas(atak, defe);
                if(sil.ram>18)yhp=yhp-(sil.atf-defe);
                break;
            case 5:
                b=vac.peleas(atak, defe);
                if(vac.ram>18)yhp=yhp-(vac.atf-defe);
                break;
            case 6:
                b=jefe.peleas(atak, defe);
                if(jefe.ram>18)yhp=yhp-(jefe.atf-defe);
                break;
            case 10:
                b=caz.peleas(atak, defe);
                if(caz.ram>18)yhp=yhp-(caz.atf-defe);
                break;
            case 11:
                 b=vbot.peleas(atak, defe);
                if(vbot.ram>18)yhp=yhp-(vbot.atf-defe);
                break;
            
                }
            if(hpe>1 && yhp>1){
            dialogo.setText(b);
            vida.setText(Integer.toString(yhp));}
            else{
                if(yhp>1){
                vida.setText(Integer.toString(yhp));
                jPanel4.setVisible(false);
                vueltas=1;
                dialogo.setText("Has derrotado a "+ Nom3.getText());
                cerrar();}
                if(hpe>1){
                    muertos.setVisible(true);
                    diedo.play();
                juego.setVisible(false);}}
        break;}
    }//GEN-LAST:event_bus_defActionPerformed

    private void sui_escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sui_escActionPerformed
        // TODO add your handling code here:
        switch(vueltas){
            case 2:
                int rem;
                if(espe>100 || inten==5){}else{
                    inten++;
                    rem=(int)Math.round(Math.random()*9);
                    if(yhp>=1 && yhp<=5){ 
                        dialogo.setText("■■ Has escapado por los pelos ■■"); 
                        hpe=0;
                        vida.setText(Integer.toString(yhp));
                        jPanel4.setVisible(false);
                        vueltas=1;
                        exp-=espe;
                        cerrar();}
                    else if(rem>=0 && rem<=3){ 
                        dialogo.setText(" No has podido escapar");
                        yhp=(yhp/3)*2;}
                    else if(rem>=4 && rem<=9){
                        dialogo.setText("■■ Has escapado ■■");
                        hpe=0;
                        vida.setText(Integer.toString(yhp));
                        jPanel4.setVisible(false);
                        vueltas=1;
                        exp-=espe;
                        cerrar();}}
                break;
        }
    }//GEN-LAST:event_sui_escActionPerformed

    private void abilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abilidadActionPerformed
        // TODO add your handling code here:
        int jj=2;
        
        yhp+=(hep/jj);
        if(yhp>hep)yhp=hep;
        vida.setText(Integer.toString(yhp));
        abilidad.setEnabled(false);
        abilidad1.setEnabled(false);
        barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra0.png")));
        habilidad=0;
        
    }//GEN-LAST:event_abilidadActionPerformed

    private void subdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subdActionPerformed
        //AUMENTO DE DEFENSA AL SUBIR LV
        if(exp>9){
        defe+=3;
        her.def+=3;
        stad.setText(Integer.toString(defe));
        def.setText(Integer.toString(defe));
        vida.setText(Integer.toString(hep)); lev++;
        nivels.setText(Integer.toString(lev));
        subirE();
        vida4.setText(Integer.toString(her.hp));
        lv.setText(Integer.toString(lev));
        exp-=10;}
        xp.setText(Integer.toString(exp));
        yhp=her.hp;
        exper.setText(Integer.toString(exp));
        if(exp<10 && vueltas==1) abilidad.setVisible(false);
    }//GEN-LAST:event_subdActionPerformed

    private void subvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subvActionPerformed
        // AUMENTO DE VIDA AL SUBIR LV
        if(exp>9){
        hep+=10;
        her.hp+=10;
        stav.setText(Integer.toString(hep));
        vida.setText(Integer.toString(hep)); lev++;
        nivels.setText(Integer.toString(lev));
        subirE();
        vida4.setText(Integer.toString(her.hp));
        lv.setText(Integer.toString(lev));
        exp-=10;}
        xp.setText(Integer.toString(exp));
        yhp=her.hp;
        exper.setText(Integer.toString(exp));
        if(exp<10 && vueltas==1) abilidad.setVisible(false);
    }//GEN-LAST:event_subvActionPerformed

    private void subaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subaActionPerformed
        // AUMENTO DE ATAQUE AL SUBIR LV
        if(exp>9){
        atak+=2;
        her.atk+=2;
        staa.setText(Integer.toString(atak));
        atk.setText(Integer.toString(atak));
        lev++;
        nivels.setText(Integer.toString(lev));
        subirE();
        lv.setText(Integer.toString(lev));
        exp-=10;}
        xp.setText(Integer.toString(exp));
        yhp=her.hp;
        exper.setText(Integer.toString(exp));
        if(exp<10 && vueltas==1) abilidad.setVisible(false);
    }//GEN-LAST:event_subaActionPerformed

    private void desplayearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplayearActionPerformed
        // TODO add your handling code here:
        AudioClip musicaa;
        musicaa = java.applet.Applet.newAudioClip(getClass().getResource("/musicass/Kirby Super Star.wav"));
        musicaa.play();
        desplayear.setVisible(false);
        playear.setVisible(true);
        
    }//GEN-LAST:event_desplayearActionPerformed

    private void playearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playearActionPerformed
        // TODO add your handling code here:
        AudioClip musicaa;
        musicaa = java.applet.Applet.newAudioClip(getClass().getResource("/musicass/Kirby Super Star.wav"));
        musicaa.stop();
        playear.setVisible(false);
        desplayear.setVisible(true);
        
    }//GEN-LAST:event_playearActionPerformed

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed
        // TODO add your handling code here:
        con.setVisible(true);
        
    }//GEN-LAST:event_configActionPerformed

    private void obtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenActionPerformed
        // TODO add your handling code here:
        colo.setBackground(Color.CYAN);
        colo1.setBackground(Color.CYAN);
        colo.setVisible(false);
        colo.setVisible(true);
        colo1.setVisible(false);
        colo1.setVisible(true);
    }//GEN-LAST:event_obtenActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        colo.setBackground(Color.GRAY);
        colo1.setBackground(Color.GRAY);
        colo.setVisible(false);
        colo.setVisible(true);
        colo1.setVisible(false);
        colo1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        colo.setBackground(Color.blue);
        colo1.setBackground(Color.blue);
        colo.setVisible(false);
        colo.setVisible(true);
        colo1.setVisible(false);
        colo1.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        colo.setBackground(Color.ORANGE);
        colo1.setBackground(Color.ORANGE);
        colo.setVisible(false);
        colo.setVisible(true);
        colo1.setVisible(false);
        colo1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void let3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_let3ActionPerformed
        // TODO add your handling code here:
        Font phone=new Font("Tahoma",Font.PLAIN, 11);
        dialogo.setFont(phone);
        nivels.setFont(phone);
        jLabel5.setFont(phone);
        jLabel10.setFont(phone);
        jLabel11.setFont(phone);
        jLabel15.setFont(phone);
        jLabel14.setFont(phone);
        jLabel16.setFont(phone);
        jLabel17.setFont(phone);
        exper.setFont(phone);
        nombrep.setFont(phone);
        abilidad.setFont(phone);
        sui_esc.setFont(phone);
        bus_def.setFont(phone);
        ava_atk.setFont(phone);
        jButton1.setFont(phone);
        suba.setFont(phone);
        subd.setFont(phone);
        subv.setFont(phone);
        Nom.setFont(phone);
        vida.setFont(phone);
        vida4.setFont(phone);
        vida3.setFont(phone);
        vida5.setFont(phone);
        atk.setFont(phone);
        def.setFont(phone);
        lv.setFont(phone);
        xp.setFont(phone);
    }//GEN-LAST:event_let3ActionPerformed

    private void let2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_let2ActionPerformed
        // TODO add your handling code here:
        Font phone=new Font("Webdings",Font.PLAIN, 11);
        dialogo.setFont(phone);
        nivels.setFont(phone);
        jLabel5.setFont(phone);
        jLabel10.setFont(phone);
        jLabel11.setFont(phone);
        jLabel15.setFont(phone);
        jLabel14.setFont(phone);
        jLabel16.setFont(phone);
        jLabel17.setFont(phone);
        exper.setFont(phone);
        nombrep.setFont(phone);
        abilidad.setFont(phone);
        sui_esc.setFont(phone);
        bus_def.setFont(phone);
        ava_atk.setFont(phone);
        jButton1.setFont(phone);
        suba.setFont(phone);
        subd.setFont(phone);
        subv.setFont(phone);
        Nom.setFont(phone);
        vida.setFont(phone);
        vida4.setFont(phone);
        vida3.setFont(phone);
        vida5.setFont(phone);
        atk.setFont(phone);
        def.setFont(phone);
        lv.setFont(phone);
        xp.setFont(phone);
    }//GEN-LAST:event_let2ActionPerformed

    private void letActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letActionPerformed
        // TODO add your handling code here:
        Font phone=new Font("Segoe Script",Font.PLAIN, 11);
        dialogo.setFont(phone);
        nivels.setFont(phone);
        jLabel5.setFont(phone);
        jLabel10.setFont(phone);
        jLabel11.setFont(phone);
        jLabel15.setFont(phone);
        jLabel14.setFont(phone);
        jLabel16.setFont(phone);
        jLabel17.setFont(phone);
        exper.setFont(phone);
        nombrep.setFont(phone);
        abilidad.setFont(phone);
        sui_esc.setFont(phone);
        bus_def.setFont(phone);
        ava_atk.setFont(phone);
        jButton1.setFont(phone);
        suba.setFont(phone);
        subd.setFont(phone);
        subv.setFont(phone);
        Nom.setFont(phone);
        vida.setFont(phone);
        vida4.setFont(phone);
        vida3.setFont(phone);
        vida5.setFont(phone);
        atk.setFont(phone);
        def.setFont(phone);
        lv.setFont(phone);
        xp.setFont(phone);
    }//GEN-LAST:event_letActionPerformed

    private void subLVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subLVActionPerformed
        // TODO add your handling code here:
        subirlv.setVisible(true);
        stad.setText(Integer.toString(defe));
        stav.setText(Integer.toString(hep));
        staa.setText(Integer.toString(atak));
        exper.setText(Integer.toString(exp));
        nombrep.setText(hero);
        nivels.setText(Integer.toString(lev));
    }//GEN-LAST:event_subLVActionPerformed

    private void izquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaMouseClicked
        // TODO add your handling code here:
        batallas(0);
    }//GEN-LAST:event_izquierdaMouseClicked

    private void enfrenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enfrenteMouseClicked
        // TODO add your handling code here:
        batallas(0);
    }//GEN-LAST:event_enfrenteMouseClicked

    private void derechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaMouseClicked
        // TODO add your handling code here:
        batallas(0);
    }//GEN-LAST:event_derechaMouseClicked

    private void retrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrocederMouseClicked
        // TODO add your handling code here:
        finav.setVisible(true);
    }//GEN-LAST:event_retrocederMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        titulo.setVisible(false);
        juego.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
try {
            FileReader leer = new FileReader("Save.txt");
            BufferedReader BR = new BufferedReader(leer);
            String cadena = "";
                try {
                    //---------------------------
                    cadena = BR.readLine();
                    asdf = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    camino = Integer.parseInt(cadena);
                    //------------------------------
                    cadena = BR.readLine();
                    btn = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    avk = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    bd = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    sues = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    pele = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    suitch = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    vueltas = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    ra = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    otro = Integer.parseInt(cadena);
                    //--------------------------------
                    cadena = BR.readLine();
                    mus = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    der = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    espe = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    inten = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    pasos = Integer.parseInt(cadena);
                    //------------------------------
                    cadena = BR.readLine();
                    atak = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    defe = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    exp = Integer.parseInt(cadena);
                    cadena = BR.readLine();
                    lev = Integer.parseInt(cadena);
                    //------------------------------
                    cadena = BR.readLine();
                    hep = Integer.parseInt(cadena);
                } catch (IOException ex) {}
       } catch (FileNotFoundException ex) {JOptionPane.showConfirmDialog(null,"No hay nada guardado", "Error", JOptionPane.OK_OPTION);}  
            titulo.setVisible(false);
            juego.setVisible(true);
            her.atk=atak;
            her.def=defe;
            her.hp=hep;
            her.lv=lev;
            her.xp=exp;
            String t3=("\n\n¿A donde vas a ir?");
                batallas(1);
                subirE();
                subLV.setVisible(true);
                pantalla.setVisible(true);
                yhp=her.hp; vida4.setText(Integer.toString(her.hp));
                vida.setText(Integer.toString(hep));
                dialogo.setText(t3); 
                jButton1.setVisible(false); 
                jPanel1.setVisible(true);
                config.setVisible(true);
                atk.setText(Integer.toString(atak));
                def.setText(Integer.toString(defe));
                lv.setText(Integer.toString(lev));
                xp.setText(Integer.toString(exp));
            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
File save = new File("save.txt");
if (save.exists()){FileOutputStream fso; 
    try {
        fso = new FileOutputStream("Save.txt");
        fso.close();
    } catch (FileNotFoundException e) {} catch (IOException ex) {}}
if(!save.exists()){try {save.createNewFile();} catch (IOException ex) {}}
try{
FileWriter escribir = new FileWriter (save,true);
PrintWriter linea = new PrintWriter(escribir);
///--------------------
linea.println(asdf);
linea.println(camino);
//--------------------
linea.println(btn);
linea.println(avk);
linea.println(bd);
linea.println(sues);
linea.println(pele);
linea.println(suitch);
linea.println(vueltas);
linea.println(ra);
linea.println(otro);
//------------------
linea.println(mus);
linea.println(der);
linea.println(espe);
linea.println(inten);
linea.println(pasos);
//-------------------
linea.println(atak);
linea.println(defe);
linea.println(exp);
linea.println(lev);
//-------------------
linea.println(hep);
//-------------------
escribir.close();}
catch(IOException ie){}
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void abilidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abilidad1ActionPerformed
        // TODO add your handling code here:
        int jj=2;
        abilidad.setEnabled(false);
        abilidad1.setEnabled(false);
        
        hpe=hpe-(atak*jj);
        vida3.setText(Integer.toString(hpe));
        barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/barra0.png")));
        habilidad=0;
        if(hpe<1){
        vida.setText(Integer.toString(yhp));
        jPanel4.setVisible(false);
        vueltas=1;
        dialogo.setText("Has derrotado a"+ Nom3.getText());
        cerrar();}
    }//GEN-LAST:event_abilidad1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel Nom3;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton abilidad;
    private javax.swing.JButton abilidad1;
    private javax.swing.JLabel atk;
    private javax.swing.JButton ava_atk;
    private javax.swing.JLabel barra;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton bus_def;
    private javax.swing.JPanel colo;
    private javax.swing.JPanel colo1;
    private javax.swing.JFrame con;
    private javax.swing.JButton config;
    private javax.swing.JLabel def;
    private javax.swing.JLabel derecha;
    private javax.swing.JButton desplayear;
    private javax.swing.JTextArea dialogo;
    private javax.swing.JLabel enfrente;
    private javax.swing.JLabel exper;
    private javax.swing.JFrame finav;
    private javax.swing.JLabel izquierda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel juego;
    private javax.swing.JButton let;
    private javax.swing.JButton let2;
    private javax.swing.JButton let3;
    private javax.swing.JLabel lv;
    private javax.swing.JPanel muertos;
    private javax.swing.JLabel nivels;
    private javax.swing.JLabel nombrep;
    private javax.swing.JButton obten;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton playear;
    private javax.swing.JLabel retroceder;
    private javax.swing.JLabel staa;
    private javax.swing.JLabel stad;
    private javax.swing.JLabel stav;
    private javax.swing.JButton subLV;
    private javax.swing.JButton suba;
    private javax.swing.JButton subd;
    private javax.swing.JFrame subirlv;
    private javax.swing.JButton subv;
    private javax.swing.JButton sui_esc;
    private javax.swing.JPanel titulo;
    private javax.swing.JLabel vaco;
    private javax.swing.JLabel vida;
    private javax.swing.JLabel vida3;
    private javax.swing.JLabel vida4;
    private javax.swing.JLabel vida5;
    private javax.swing.JLabel xp;
    // End of variables declaration//GEN-END:variables
//CIERRA LOS ESTADPS DE PELEA Y REGRESA AL ESTADO ANTERIOR
    public void cerrar(){
        enfrente.setVisible(false);
        derecha.setVisible(false);
        izquierda.setVisible(false);
        vaco.setVisible(false);
        ava_atk.setVisible(false); 
        bus_def.setVisible(false); 
        sui_esc.setVisible(false); 
        abilidad.setVisible(false);
        abilidad1.setVisible(false);
        barra.setVisible(false);
        jButton1.setVisible(true); 
        jPanel1.setVisible(false); btn=6;
        exp+=espe;
        her.xp+=espe;
    }
    
    public void subirE(){
        if(arc.lv<lev){
            jefe.nivel(lev);
            caz.nivel(lev);
            sold.nivel(lev);
            arc.nivel(lev);
            caba.nivel(lev);
            sil.nivel(lev);
            pic.nivel(lev);
            vac.nivel(lev);
            
        }
    }
    public void jefazos(){
        a=("JAJAJAJA\n"
                + "al fin nos encontramos T-X2\n"
                + "sabes, eres tenas, eres fuerte\n"
                + "eres impresionante, incluso mataste a"
                + "mi chef...\n"
                + "bueno, es una lastima que tenga que matarte\n"
                + "¡MUERE!");
         dialogo.setText(a);
         diedo = java.applet.Applet.newAudioClip(getClass().getResource("/musicass/failsound.wav"));
        choy = java.applet.Applet.newAudioClip(getClass().getResource("/musicass/Soul of Cinder.wav"));
        choy.stop();
        choy.loop();
        
    }
    public void vacabot(){
        a=("REBELDE????: \nbip bip bip REGISTRO VACUNO ACTIVADO\n"
                + " ELIMINAR... REBELDES...\n"
                + "ESPERA... YO SER REBELDE...\n"
                + "\nAUTOELIMINACIÓN EN 3..2...\n"
                + "MUUUUUUUUM\n"
                + "... bip bip\n"
                + "ERROR VACABOT.EXE NOT FOUND");
         dialogo.setText(a);
    }
    public void cazador(){
        a=("CAZARRECOMPENSAS: \n¿Así que erres tu el que osa desafiarr al grran CHOY? \n"
                + " Bueno, no serrá porr mucho...sabes...\n"
                + "Soy famoso porr mis fabulosas hamburrguesas\n"
                + "\n¿Porr que no vienes? estás invitado...\n"
                + "ya que...\n"
                + "Después de todo... ¡tú ERRES el menú¡");
         dialogo.setText(a);
         
         diedo = java.applet.Applet.newAudioClip(getClass().getResource("/musicass/failsound.wav"));
        caza = java.applet.Applet.newAudioClip(getClass().getResource("/musicass/undyne.wav"));
        caza.stop();
        caza.loop();
    }
    public void batallas(int z){
        pasos++;
        asdf=(int)Math.round(Math.random()*4);
        if(pasos==2001){
        }else{
        if(pasos==2000){
            vueltas=2;
            pele=6;
            pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/1 way.jpg")));
            jPanel1.setVisible(true);
            vaco.setVisible(true);
            ava_atk.setVisible(true);
            bus_def.setVisible(true);
            abilidad.setVisible(true);
            abilidad1.setVisible(true);
            barra.setVisible(true);
            sui_esc.setVisible(false);
            enfrente.setVisible(false);
            izquierda.setVisible(false);
            derecha.setVisible(false);
            retroceder.setVisible(false);
            jPanel4.setVisible(true);
            hpe=jefe.hp;
            vida5.setText(Integer.toString(hpe));
        dialogo.setText(a);
        Nom3.setText(jefe.nom);
        hpe=jefe.hp;
        vida3.setText(Integer.toString(hpe));
        vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Choy1.png")));
        espe=jefe.xp;
            jefazos();
        }
        else{
        if(pasos==700){
            vueltas=2;
            pele=10;
            pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/1 way.jpg")));
            jPanel1.setVisible(true);
            vaco.setVisible(true);
            ava_atk.setVisible(true);
            bus_def.setVisible(true);
            abilidad.setVisible(true);
            abilidad1.setVisible(true);
            barra.setVisible(true);
            sui_esc.setVisible(false);
            enfrente.setVisible(false);
            izquierda.setVisible(false);
            derecha.setVisible(false);
            retroceder.setVisible(false);
            jPanel4.setVisible(true);
            hpe=caz.hp;
            vida5.setText(Integer.toString(hpe));
        dialogo.setText(a);
        Nom3.setText(caz.nom);
        hpe=caz.hp;
        vida3.setText(Integer.toString(hpe));
        vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Cazarrecompensas.png")));
        espe=caz.xp;
            cazador();
        }
        else{
            if(pasos==50){
            vueltas=2;
            pele=11;
            pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/1 way.jpg")));
            jPanel1.setVisible(true);
            vaco.setVisible(true);
            ava_atk.setVisible(true);
            bus_def.setVisible(true);
            abilidad.setVisible(true);
            abilidad1.setVisible(true);
            barra.setVisible(true);
            sui_esc.setVisible(false);
            enfrente.setVisible(false);
            izquierda.setVisible(false);
            derecha.setVisible(false);
            retroceder.setVisible(false);
            jPanel4.setVisible(true);
            hpe=vbot.hp;
            vida5.setText(Integer.toString(hpe));
        dialogo.setText(a);
        Nom3.setText(vbot.nom);
        hpe=vbot.hp;
        vida3.setText(Integer.toString(hpe));
        vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Vacabot.png")));
        espe=vbot.xp;
            vacabot();
        }else{
        if((asdf==0) && (z==0)){
            vueltas=2;
            pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/1 way.jpg")));
            jPanel1.setVisible(true);
            vaco.setVisible(true);
            ava_atk.setVisible(true);
            bus_def.setVisible(true);
            abilidad.setVisible(true);
            abilidad1.setVisible(true);
            barra.setVisible(true);
            sui_esc.setVisible(true);
            enfrente.setVisible(false);
            izquierda.setVisible(false);
            derecha.setVisible(false);
            retroceder.setVisible(false);
            //ALEATORIZA EL ENEMIGO A COMBATIR
            pele = (int) Math.round(Math.random() * 5);
            //HACE VISIBLE LAS STATS ENEMIGAS
            jPanel4.setVisible(true);
            //INICIALIZACION DEL ENEMIGO SEGUN QUIEN FUE SELECCIONADO
            switch (pele) {
                case 0:
                    a = sold.present();
                    dialogo.setText(a);
                    Nom3.setText(sold.nom);
                    hpe=sold.hp;
                    vida3.setText(Integer.toString(hpe));
                    vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Soldado.png"))); 
                    espe=sold.xp;
                    break;
                case 1:
                    a = arc.present();
                    dialogo.setText(a);
                    Nom3.setText(arc.nom);
                    hpe=arc.hp;
                    vida3.setText(Integer.toString(hpe));
                    vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Arquero.png")));
                    espe=arc.xp;
                    break;
                case 2:
                    a = caba.present();
                    dialogo.setText(a);
                    Nom3.setText(caba.nom);
                    hpe=caba.hp;
                    vida3.setText(Integer.toString(hpe));
                    vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Caballero.png"))); 
                    espe=caba.xp;
                    break;
                case 3:
                    a = pic.present();
                    dialogo.setText(a);
                    Nom3.setText(pic.nom);
                    hpe=pic.hp;
                    vida3.setText(Integer.toString(hpe));
                    vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Picaro.png"))); 
                    espe=pic.xp;
                    break;
                case 4:
                    a = sil.present();
                    dialogo.setText(a);
                    Nom3.setText(sil.nom);
                    hpe=sil.hp;
                    vida3.setText(Integer.toString(hpe));
                    vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/vaaco.png")));
                    espe=sil.xp;
                    break;
                case 5:
                    a = vac.present();
                    dialogo.setText(a);
                    Nom3.setText(vac.nom);
                    hpe=vac.hp;
                    vida3.setText(Integer.toString(hpe));
                    vaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/Vaca.png")));                           
                    espe=vac.xp;
                    break;}
            vida5.setText(Integer.toString(hpe));
        }else{
            camino=(int)Math.round(Math.random()*3);
            retroceder.setVisible(true);
        switch(camino){
            case 0://3 caminos
                enfrente.setVisible(true);
                izquierda.setVisible(true);
                derecha.setVisible(true);
                pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/3 way.png")));
                break;
            case 1://izquierda-arriba
                enfrente.setVisible(true);
                izquierda.setVisible(true);
                derecha.setVisible(false);
                pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/2 way(izquierda-enfrente).png")));
                break;
            case 2://derecha-arriba
                enfrente.setVisible(true);
                izquierda.setVisible(false);
                derecha.setVisible(true);
                pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/2 way(derecha-enfremte).png")));
                break;
            case 3://izquierda-derecha
                enfrente.setVisible(false);
                izquierda.setVisible(true);
                derecha.setVisible(true);
                pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code final/2 way(izquierda-derecha).png")));
                break;
        }
        }
    }}
    }}}
}
